export interface Tool {
  slug: string;
  category: string;
  emoji: string;
  labelKey: string;
  href: string;
  available: boolean;
  icon?: string;
  nameKo?: string;
  nameEn?: string;
  descKo?: string;
  descEn?: string;
  categoryNameKo?: string;
  categoryNameEn?: string;
  searchKeywords?: string[];
}

export const tools: Tool[] = [
  // Performance
  { slug: 'ttfb-check', category: 'performance', emoji: '🚀', labelKey: 'Ttfb.title', href: '/utilities/performance/ttfb-check', available: true, icon: 'Activity', nameKo: 'TTFB 체크', nameEn: 'TTFB Checker', descKo: '웹사이트 응답 속도 측정', descEn: 'Measure website response time', categoryNameKo: '성능/모니터링', categoryNameEn: 'Performance', searchKeywords: ['속도', '응답', 'ttfb', 'performance', 'speed'] },
  { slug: 'sla-uptime-calc', category: 'performance', emoji: '📊', labelKey: 'PerformanceBoard.sla-uptime-calc.title', href: '/utilities/performance/sla-uptime-calc', available: true, icon: 'BarChart3', nameKo: 'SLA 가동률 계산기', nameEn: 'SLA Uptime Calculator', descKo: '서비스 가동 시간 및 SLA 계산', descEn: 'Calculate service uptime and SLA', categoryNameKo: '성능/모니터링', categoryNameEn: 'Performance', searchKeywords: ['sla', '가동률', 'uptime', '서버'] },
  { slug: 'carbon-footprint', category: 'performance', emoji: '🌿', labelKey: 'PerformanceBoard.carbon-footprint.title', href: '/utilities/performance/carbon-footprint', available: true, icon: 'Leaf', nameKo: '탄소발자국 계산기', nameEn: 'Carbon Footprint Calculator', descKo: '개인 탄소 배출량 계산', descEn: 'Calculate personal carbon emissions', categoryNameKo: '성능/모니터링', categoryNameEn: 'Performance', searchKeywords: ['탄소', '환경', 'carbon', 'co2', 'emission'] },
  { slug: 'core-web-vitals', category: 'performance', emoji: '📐', labelKey: 'PerformanceBoard.core-web-vitals.title', href: '/utilities/performance/core-web-vitals', available: true, icon: 'Gauge', nameKo: 'Core Web Vitals 측정', nameEn: 'Core Web Vitals Checker', descKo: '구글 성능 지표 점수 확인', descEn: 'Check Google performance metrics', categoryNameKo: '성능/모니터링', categoryNameEn: 'Performance', searchKeywords: ['cwv', 'lcp', 'fid', 'cls', 'google', '성능'] },

  // Document
  { slug: 'hwp-pdf-converter', category: 'document', emoji: '📄', labelKey: 'DocumentBoard.hwp-pdf-converter.title', href: '/utilities/document/hwp-pdf-converter', available: true, icon: 'File', nameKo: 'HWP→PDF 변환기', nameEn: 'HWP to PDF Converter', descKo: '한글 파일을 PDF로 변환', descEn: 'Convert HWP files to PDF', categoryNameKo: '문서 변환/편집', categoryNameEn: 'Document', searchKeywords: ['hwp', '한글', 'pdf', '변환', 'convert'] },
  { slug: 'img-pdf-converter', category: 'document', emoji: '🖼️', labelKey: 'DocumentBoard.img-pdf-converter.title', href: '/utilities/document/img-pdf-converter', available: true, icon: 'Image', nameKo: '이미지→PDF 변환기', nameEn: 'Image to PDF Converter', descKo: '이미지 파일을 PDF로 변환', descEn: 'Convert images to PDF', categoryNameKo: '문서 변환/편집', categoryNameEn: 'Document', searchKeywords: ['이미지', '사진', 'jpg', 'png', 'pdf', '변환'] },
  { slug: 'pdf-masking', category: 'document', emoji: '🛡️', labelKey: 'DocumentBoard.pdf-masking.title', href: '/utilities/document/pdf-masking', available: true, icon: 'Shield', nameKo: 'PDF 민감정보 마스킹', nameEn: 'PDF Masking Tool', descKo: 'PDF 내 개인정보 블러 처리', descEn: 'Blur personal info in PDF', categoryNameKo: '문서 변환/편집', categoryNameEn: 'Document', searchKeywords: ['pdf', '마스킹', '개인정보', '블러', 'masking', 'privacy'] },

  // Finance
  { slug: 'vat-calc', category: 'finance', emoji: '🧾', labelKey: 'FinanceBoard.vat-calc.title', href: '/utilities/finance/vat-calc', available: true, icon: 'Receipt', nameKo: '부가세(VAT) 계산기', nameEn: 'VAT Calculator', descKo: '공급가·부가세·합계 즉시 계산', descEn: 'Calculate supply price, VAT and total instantly', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['부가세', 'vat', '세금', 'tax', '공급가'] },
  { slug: 'percentage-calc', category: 'finance', emoji: '🔢', labelKey: 'FinanceBoard.percentage-calc.title', href: '/utilities/finance/percentage-calc', available: true, icon: 'Calculator', nameKo: '퍼센트 계산기', nameEn: 'Percentage Calculator', descKo: '할인율·증감률·퍼센트 계산', descEn: 'Calculate discount, change and percentage', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['퍼센트', 'percent', '할인', '증감', '비율', 'ratio'] },
  { slug: 'interest-calc', category: 'finance', emoji: '💰', labelKey: 'FinanceBoard.interest-calc.title', href: '/utilities/finance/interest-calc', available: true, icon: 'TrendingUp', nameKo: '이자 계산기', nameEn: 'Interest Calculator', descKo: '단리·복리 이자 및 원리금 계산', descEn: 'Calculate simple and compound interest', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['이자', '금리', '적금', '예금', 'interest', 'compound', '단리', '복리'] },
  { slug: 'tax-33-calc', category: 'finance', emoji: '💼', labelKey: 'FinanceBoard.tax-33-calc.title', href: '/utilities/finance/tax-33-calc', available: true, icon: 'Receipt', nameKo: '3.3% 세금 계산기', nameEn: '3.3% Tax Calculator', descKo: '프리랜서 원천징수 실수령액 계산', descEn: 'Calculate freelancer withholding tax', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['3.3%', '원천징수', '프리랜서', '세금', 'freelancer', 'withholding'] },
  { slug: 'salary-calc', category: 'finance', emoji: '💵', labelKey: 'FinanceBoard.salary-calc.title', href: '/utilities/finance/salary-calc', available: true, icon: 'Wallet', nameKo: '급여 실수령액 계산기', nameEn: 'Salary Net Pay Calculator', descKo: '시급·잔업·특근 포함 실수령액', descEn: 'Calculate net pay with overtime', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['급여', '월급', '실수령', '잔업', '시급', 'salary', 'wage'] },
  { slug: 'smart-percent', category: 'finance', emoji: '💹', labelKey: 'FinanceBoard.smart-percent.title', href: '/utilities/finance/smart-percent', available: true, icon: 'PieChart', nameKo: '스마트 퍼센트 도구', nameEn: 'Smart Percent Tool', descKo: '복합 퍼센트 및 역산 계산', descEn: 'Advanced percentage and reverse calculation', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['퍼센트', '역산', '비율', 'smart percent'] },
  { slug: 'freelance-rate-calculator', category: 'finance', emoji: '⚡', labelKey: 'FinanceBoard.freelance-rate-calculator.title', href: '/utilities/finance/freelance-rate-calculator', available: true, icon: 'Briefcase', nameKo: '프리랜서 단가 계산기', nameEn: 'Freelance Rate Calculator', descKo: '목표 수익 기반 시간당 단가 산출', descEn: 'Calculate hourly rate from income goal', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['프리랜서', '단가', '시급', 'freelance', 'rate'] },
  { slug: 'invoice-maker', category: 'finance', emoji: '🧾', labelKey: 'FinanceBoard.invoice-maker.title', href: '/utilities/finance/invoice-maker', available: true, icon: 'FileText', nameKo: '견적서·청구서 생성기', nameEn: 'Invoice Maker', descKo: '전문 견적서 및 청구서 제작', descEn: 'Create professional invoices', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['청구서', '견적서', 'invoice', '계산서', '영수증'] },
  { slug: 'exchange-rate', category: 'finance', emoji: '💱', labelKey: 'FinanceBoard.exchange-rate.title', href: '/utilities/finance/exchange-rate', available: true, icon: 'ArrowLeftRight', nameKo: '실시간 환율 변환기', nameEn: 'Real-time Currency Converter', descKo: '20개 통화 즉시 변환, 30일 추이', descEn: 'Convert 20 currencies with 30-day chart', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['환율', '달러', '원화', '환전', 'currency', 'dollar', 'exchange', '엔화', '유로'] },
  { slug: 'coin-profit', category: 'finance', emoji: '🪙', labelKey: 'FinanceBoard.coin-profit.title', href: '/utilities/finance/coin-profit', available: true, icon: 'Coins', nameKo: '코인 수익 계산기', nameEn: 'Crypto Profit Calculator', descKo: '암호화폐 매수·매도 수익 계산', descEn: 'Calculate crypto buy/sell profit', categoryNameKo: '결제/핀테크', categoryNameEn: 'Finance', searchKeywords: ['코인', '비트코인', '암호화폐', '수익', 'crypto', 'bitcoin', 'profit'] },

  // Productivity
  { slug: 'pomodoro', category: 'productivity', emoji: '🍅', labelKey: 'ProductivityBoard.pomodoro.title', href: '/utilities/productivity/pomodoro', available: true, icon: 'Timer', nameKo: '포모도로 타이머', nameEn: 'Pomodoro Timer', descKo: '집중력 향상 뽀모도로 기법 타이머', descEn: 'Focus timer using Pomodoro technique', categoryNameKo: '생산성', categoryNameEn: 'Productivity', searchKeywords: ['포모도로', '타이머', '집중', '공부', 'timer', 'focus', 'pomodoro'] },
  { slug: 'world-time', category: 'productivity', emoji: '🌍', labelKey: 'ProductivityBoard.world-time.title', href: '/utilities/productivity/world-time', available: true, icon: 'Globe2', nameKo: '세계 시간 변환기', nameEn: 'World Time Converter', descKo: '전 세계 주요 도시 시간 비교', descEn: 'Compare time across major world cities', categoryNameKo: '생산성', categoryNameEn: 'Productivity', searchKeywords: ['세계시간', '시차', 'time zone', 'timezone', '뉴욕', '런던', '도쿄'] },
  { slug: 'resume-helper', category: 'productivity', emoji: '📝', labelKey: 'ProductivityBoard.resume-helper.title', href: '/utilities/productivity/resume-helper', available: true, icon: 'FileText', nameKo: '이력서 도우미', nameEn: 'Resume Helper', descKo: 'AI 기반 이력서 작성 가이드', descEn: 'AI-powered resume writing guide', categoryNameKo: '생산성', categoryNameEn: 'Productivity', searchKeywords: ['이력서', '자소서', 'resume', 'cv', '취업', 'job'] },
  { slug: 'excel-mapper', category: 'productivity', emoji: '📊', labelKey: 'ProductivityBoard.excel-mapper.title', href: '/utilities/productivity/excel-mapper', available: true, icon: 'Table2', nameKo: '엑셀 컬럼 매퍼', nameEn: 'Excel Column Mapper', descKo: '엑셀 컬럼 매핑 및 변환 도구', descEn: 'Map and transform Excel columns', categoryNameKo: '생산성', categoryNameEn: 'Productivity', searchKeywords: ['엑셀', 'excel', 'csv', '매핑', 'mapping', 'column'] },
  { slug: 'bomb-pad', category: 'productivity', emoji: '💣', labelKey: 'ProductivityBoard.bomb-pad.title', href: '/utilities/productivity/bomb-pad', available: true, icon: 'Flame', nameKo: '폭탄 메모장', nameEn: 'Bomb Notepad', descKo: '일정 시간 후 내용이 사라지는 메모장', descEn: 'Self-destructing notepad with timer', categoryNameKo: '생산성', categoryNameEn: 'Productivity', searchKeywords: ['메모', 'notepad', '타이머', '폭탄', 'timer', '임시'] },
  { slug: 'solar-master', category: 'productivity', emoji: '☀️', labelKey: 'ProductivityBoard.solar-master.title', href: '/utilities/productivity/solar-master', available: true, icon: 'Sun', nameKo: '일출·일몰 계산기', nameEn: 'Sunrise/Sunset Calculator', descKo: '위치 기반 일출·일몰·낮 길이 계산', descEn: 'Calculate sunrise, sunset and daylight', categoryNameKo: '생산성', categoryNameEn: 'Productivity', searchKeywords: ['일출', '일몰', '태양', 'sunrise', 'sunset', 'solar'] },

  // Design
  { slug: 'logo-favicon', category: 'design', emoji: '🎨', labelKey: 'DesignBoard.logo-favicon.title', href: '/utilities/design/logo-favicon', available: true, icon: 'Palette', nameKo: '로고·파비콘 생성기', nameEn: 'Logo & Favicon Maker', descKo: '텍스트 기반 로고 및 파비콘 생성', descEn: 'Create text-based logos and favicons', categoryNameKo: 'UX/디자인', categoryNameEn: 'Design', searchKeywords: ['로고', '파비콘', 'logo', 'favicon', '아이콘', 'icon'] },
  { slug: 'color-palette', category: 'design', emoji: '🎯', labelKey: 'DesignBoard.color-palette.title', href: '/utilities/design/color-palette', available: true, icon: 'Swatches', nameKo: '색상 팔레트 생성기', nameEn: 'Color Palette Generator', descKo: '조화로운 색상 팔레트 자동 생성', descEn: 'Auto-generate harmonious color palettes', categoryNameKo: 'UX/디자인', categoryNameEn: 'Design', searchKeywords: ['색상', '팔레트', 'color', 'palette', '컬러'] },
  { slug: 'font-preview', category: 'design', emoji: '🔤', labelKey: 'DesignBoard.font-preview.title', href: '/utilities/design/font-preview', available: true, icon: 'Type', nameKo: '폰트 미리보기', nameEn: 'Font Preview Tool', descKo: '구글 폰트 실시간 미리보기', descEn: 'Preview Google Fonts in real time', categoryNameKo: 'UX/디자인', categoryNameEn: 'Design', searchKeywords: ['폰트', 'font', '글꼴', '타이포', 'typography', 'google fonts'] },
  { slug: 'formation-planner', category: 'design', emoji: '🕴️', labelKey: 'DesignBoard.formation-planner.title', href: '/utilities/design/formation-planner', available: true, icon: 'Users', nameKo: '대형 배치 플래너', nameEn: 'Formation Planner', descKo: '팀·공연 대형 배치 시각화 도구', descEn: 'Visualize team or performance formations', categoryNameKo: 'UX/디자인', categoryNameEn: 'Design', searchKeywords: ['대형', '배치', 'formation', '플래너', '팀'] },
  { slug: 'photo-batch-master', category: 'design', emoji: '📸', labelKey: 'DesignBoard.photo-batch-master.title', href: '/utilities/design/photo-batch-master', available: true, icon: 'Images', nameKo: '사진 일괄 편집기', nameEn: 'Photo Batch Editor', descKo: '여러 사진 일괄 리사이즈·필터', descEn: 'Batch resize and filter photos', categoryNameKo: 'UX/디자인', categoryNameEn: 'Design', searchKeywords: ['사진', '이미지', 'batch', '일괄', '편집', 'resize', 'filter'] },
  { slug: 'feedback', category: 'design', emoji: '💬', labelKey: 'DesignBoard.feedback.title', href: '/utilities/design/feedback', available: true, icon: 'MessageSquare', nameKo: '피드백 위젯', nameEn: 'Feedback Widget', descKo: '웹사이트 피드백 수집 위젯', descEn: 'Feedback collection widget for websites', categoryNameKo: 'UX/디자인', categoryNameEn: 'Design', searchKeywords: ['피드백', 'feedback', '위젯', 'widget'] },

  // Marketing
  { slug: 'osmu-formatter', category: 'marketing', emoji: '📤', labelKey: 'MarketingBoard.osmu-formatter.title', href: '/utilities/marketing/osmu-formatter', available: true, icon: 'Share2', nameKo: 'OSMU 포맷터', nameEn: 'OSMU Formatter', descKo: '콘텐츠 플랫폼별 자동 재포맷', descEn: 'Auto-reformat content for each platform', categoryNameKo: 'AI/마케팅', categoryNameEn: 'Marketing', searchKeywords: ['osmu', '콘텐츠', 'SNS', '포맷', '마케팅', 'marketing'] },
  { slug: 'hashtag-generator', category: 'marketing', emoji: '🏷️', labelKey: 'MarketingBoard.hashtag-generator.title', href: '/utilities/marketing/hashtag-generator', available: true, icon: 'Hash', nameKo: '해시태그 생성기', nameEn: 'Hashtag Generator', descKo: '인스타그램·트위터 해시태그 자동 생성', descEn: 'Auto-generate hashtags for Instagram/Twitter', categoryNameKo: 'AI/마케팅', categoryNameEn: 'Marketing', searchKeywords: ['해시태그', 'hashtag', '인스타', 'instagram', 'twitter', 'SNS'] },
  { slug: 'qr-generator', category: 'marketing', emoji: '🔗', labelKey: 'MarketingBoard.qr-generator.title', href: '/utilities/marketing/qr-generator', available: true, icon: 'QrCode', nameKo: 'QR코드 생성기', nameEn: 'QR Code Generator', descKo: 'URL·텍스트·연락처 QR코드 생성', descEn: 'Generate QR codes for URL, text, contacts', categoryNameKo: 'AI/마케팅', categoryNameEn: 'Marketing', searchKeywords: ['qr', '큐알', 'qr코드', 'qrcode', '바코드', '링크'] },
  { slug: 'shorturl', category: 'marketing', emoji: '✂️', labelKey: 'MarketingBoard.shorturl.title', href: '/utilities/marketing/shorturl', available: true, icon: 'Link2', nameKo: 'URL 단축기', nameEn: 'URL Shortener', descKo: '긴 URL을 짧게 단축', descEn: 'Shorten long URLs instantly', categoryNameKo: 'AI/마케팅', categoryNameEn: 'Marketing', searchKeywords: ['단축url', 'url', '링크', 'shorturl', 'bitly'] },
  { slug: 'quiz-builder', category: 'marketing', emoji: '🧠', labelKey: 'MarketingBoard.quiz-builder.title', href: '/utilities/marketing/quiz-builder', available: true, icon: 'HelpCircle', nameKo: '퀴즈 빌더', nameEn: 'Quiz Builder', descKo: '인터랙티브 퀴즈 생성 도구', descEn: 'Create interactive quizzes', categoryNameKo: 'AI/마케팅', categoryNameEn: 'Marketing', searchKeywords: ['퀴즈', 'quiz', '문제', 'builder', '설문'] },

  // Lifestyle
  { slug: 'gpa-calc', category: 'lifestyle', emoji: '🎓', labelKey: 'LifestyleBoard.gpa-calc.title', href: '/utilities/lifestyle/gpa-calc', available: true, icon: 'GraduationCap', nameKo: '학점(GPA) 계산기', nameEn: 'GPA Calculator', descKo: '대학 학점 평균 계산', descEn: 'Calculate college GPA', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['학점', 'gpa', '성적', '대학', 'grade'] },
  { slug: 'dday-calc', category: 'lifestyle', emoji: '📅', labelKey: 'LifestyleBoard.dday-calc.title', href: '/utilities/lifestyle/dday-calc', available: true, icon: 'CalendarDays', nameKo: 'D-Day 계산기', nameEn: 'D-Day Calculator', descKo: '날짜 차이 및 D-Day 카운트다운', descEn: 'Count days and D-Day countdown', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['디데이', 'dday', '날짜', 'countdown', '기념일'] },
  { slug: 'age-calc', category: 'lifestyle', emoji: '🎂', labelKey: 'LifestyleBoard.age-calc.title', href: '/utilities/lifestyle/age-calc', available: true, icon: 'Cake', nameKo: '나이 계산기', nameEn: 'Age Calculator', descKo: '만나이·한국나이·개월수 계산', descEn: 'Calculate Korean and international age', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['나이', '만나이', '생일', 'age', 'birthday'] },
  { slug: 'bmi-calc', category: 'lifestyle', emoji: '⚖️', labelKey: 'LifestyleBoard.bmi-calc.title', href: '/utilities/lifestyle/bmi-calc', available: true, icon: 'Activity', nameKo: 'BMI 계산기', nameEn: 'BMI Calculator', descKo: '체질량지수 및 표준체중 계산', descEn: 'Calculate BMI and ideal weight', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['bmi', '체중', '비만', '다이어트', 'weight', 'height'] },
  { slug: 'mbti-test', category: 'lifestyle', emoji: '🌊', labelKey: 'LifestyleBoard.mbti-test.title', href: '/utilities/lifestyle/mbti-test', available: true, icon: 'Brain', nameKo: 'MBTI 테스트', nameEn: 'MBTI Test', descKo: '간단한 MBTI 성격유형 검사', descEn: 'Quick MBTI personality type test', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['mbti', '성격', '유형', 'personality', '심리'] },
  { slug: 'pet-calorie', category: 'lifestyle', emoji: '🐾', labelKey: 'LifestyleBoard.pet-calorie.title', href: '/utilities/lifestyle/pet-calorie', available: true, icon: 'PawPrint', nameKo: '반려동물 칼로리 계산기', nameEn: 'Pet Calorie Calculator', descKo: '강아지·고양이 하루 칼로리 계산', descEn: 'Calculate daily calories for dogs and cats', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['반려동물', '강아지', '고양이', '칼로리', 'pet', 'calorie', 'dog', 'cat'] },
  { slug: 'aquarium-calc', category: 'lifestyle', emoji: '🐠', labelKey: 'LifestyleBoard.aquarium-calc.title', href: '/utilities/lifestyle/aquarium-calc', available: true, icon: 'Fish', nameKo: '수족관 계산기', nameEn: 'Aquarium Calculator', descKo: '어항 물 용량·어종 수 계산', descEn: 'Calculate aquarium water volume and fish capacity', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['수족관', '어항', '물고기', 'aquarium', 'fish', 'water'] },
  { slug: 'fortune-prompt', category: 'lifestyle', emoji: '🔮', labelKey: 'LifestyleBoard.fortune-prompt.title', href: '/utilities/lifestyle/fortune-prompt', available: true, icon: 'Sparkles', nameKo: '오늘의 운세', nameEn: 'Fortune Prompt', descKo: 'AI 기반 오늘의 운세 및 타로', descEn: 'AI-powered daily fortune and tarot', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['운세', '타로', 'fortune', 'tarot', '오늘', '점'] },
  { slug: 'color-coordinator', category: 'lifestyle', emoji: '🧥', labelKey: 'LifestyleBoard.color-coordinator.title', href: '/utilities/lifestyle/color-coordinator', available: true, icon: 'Shirt', nameKo: '코디 색상 추천', nameEn: 'Color Coordinator', descKo: '퍼스널 컬러 기반 코디 추천', descEn: 'Outfit color coordination recommendations', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['코디', '색상', '퍼스널컬러', '패션', 'fashion', 'color', 'outfit'] },
  { slug: 'apnea-trainer', category: 'lifestyle', emoji: '🫁', labelKey: 'LifestyleBoard.apnea-trainer.title', href: '/utilities/lifestyle/apnea-trainer', available: true, icon: 'Wind', nameKo: '잠수 훈련 타이머', nameEn: 'Apnea Trainer', descKo: '숨참기·잠수 훈련 타이머', descEn: 'Breath-hold and apnea training timer', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['잠수', '숨참기', '다이빙', 'apnea', 'breathing', 'timer'] },
  { slug: 'saju-compatibility', category: 'lifestyle', emoji: '💕', labelKey: 'LifestyleBoard.saju-compatibility.title', href: '/utilities/lifestyle/saju-compatibility', available: true, icon: 'Heart', nameKo: '사주 궁합 계산기', nameEn: 'Saju Compatibility', descKo: '음양오행 기반 궁합 계산', descEn: 'Korean saju-based compatibility check', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['궁합', '사주', '사주팔자', '운명', 'compatibility', 'love'] },
  { slug: 'ac-capacity-calc', category: 'lifestyle', emoji: '❄️', labelKey: 'LifestyleBoard.ac-capacity-calc.title', href: '/utilities/lifestyle/ac-capacity-calc', available: true, icon: 'Thermometer', nameKo: '에어컨 용량 계산기', nameEn: 'AC Capacity Calculator', descKo: '방 크기 기반 에어컨 용량 추천', descEn: 'Recommend AC capacity based on room size', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['에어컨', '냉방', 'ac', '평수', '용량', 'BTU'] },
  { slug: '30day-challenge', category: 'lifestyle', emoji: '✅', labelKey: 'LifestyleBoard.30day-challenge.title', href: '/utilities/lifestyle/30day-challenge', available: true, icon: 'CheckCircle', nameKo: '30일 챌린지 트래커', nameEn: '30-Day Challenge Tracker', descKo: '30일 목표 달성 체크리스트', descEn: 'Track your 30-day challenge goals', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['챌린지', '30일', '도전', 'challenge', 'habit', '루틴'] },
  { slug: 'nickname', category: 'lifestyle', emoji: '🏷️', labelKey: 'LifestyleBoard.nickname.title', href: '/utilities/lifestyle/nickname', available: true, icon: 'Tag', nameKo: '닉네임 생성기', nameEn: 'Nickname Generator', descKo: '랜덤 닉네임 및 아이디 생성', descEn: 'Generate random nicknames and IDs', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['닉네임', '아이디', '이름', 'nickname', 'username', 'random'] },
  { slug: 'gym-plate-calc', category: 'lifestyle', emoji: '🏋️', labelKey: 'LifestyleBoard.gym-plate-calc.title', href: '/utilities/lifestyle/gym-plate-calc', available: true, icon: 'Dumbbell', nameKo: '바벨 플레이트 계산기', nameEn: 'Gym Plate Calculator', descKo: '바벨 무게 플레이트 조합 계산', descEn: 'Calculate barbell plate combinations', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['헬스', '바벨', '플레이트', 'gym', 'barbell', 'plate', '운동', 'weight'] },
  { slug: 'teto-egen-test', category: 'lifestyle', emoji: '🧬', labelKey: 'LifestyleBoard.teto-egen-test.title', href: '/utilities/lifestyle/teto-egen-test', available: true, icon: 'Users', nameKo: '테토-에겐 테스트', nameEn: 'Teto-Egen Test', descKo: '테토형·에겐형 성격 유형 검사', descEn: 'Teto-Egen personality type test', categoryNameKo: '라이프스타일/건강', categoryNameEn: 'Lifestyle', searchKeywords: ['테토', '에겐', '성격', '유형', 'teto', 'egen', 'mbti'] },

  // Security
  { slug: 'privacy-masking', category: 'security', emoji: '🔒', labelKey: 'SecurityBoard.privacy-masking.title', href: '/utilities/security/privacy-masking', available: true, icon: 'ShieldCheck', nameKo: '개인정보 마스킹', nameEn: 'Privacy Masking', descKo: '주민번호·전화번호 등 개인정보 마스킹', descEn: 'Mask personal info like ID numbers', categoryNameKo: '보안/프라이버시', categoryNameEn: 'Security', searchKeywords: ['개인정보', '마스킹', '주민번호', 'masking', 'privacy', '보안'] },
  { slug: 'password-generator', category: 'security', emoji: '🔑', labelKey: 'SecurityBoard.password-generator.title', href: '/utilities/security/password-generator', available: true, icon: 'Key', nameKo: '비밀번호 생성기', nameEn: 'Password Generator', descKo: '강력한 랜덤 비밀번호 생성', descEn: 'Generate strong random passwords', categoryNameKo: '보안/프라이버시', categoryNameEn: 'Security', searchKeywords: ['비밀번호', '패스워드', 'password', '보안', 'random', '생성'] },
  { slug: 'url-safety', category: 'security', emoji: '🛡️', labelKey: 'SecurityBoard.url-safety.title', href: '/utilities/security/url-safety', available: true, icon: 'ShieldAlert', nameKo: 'URL 안전도 검사', nameEn: 'URL Safety Checker', descKo: '악성·피싱 URL 위험도 분석', descEn: 'Analyze URL for malicious or phishing risk', categoryNameKo: '보안/프라이버시', categoryNameEn: 'Security', searchKeywords: ['url', '링크', '피싱', '악성', 'safety', 'phishing', 'malware'] },

  // Utility
  { slug: 'wordle', category: 'utility', emoji: '🎮', labelKey: 'UtilityBoard.wordle.title', href: '/utilities/utility/wordle', available: true, icon: 'Gamepad2', nameKo: '워들 게임', nameEn: 'Wordle Game', descKo: '5글자 단어 맞추기 퍼즐 게임', descEn: '5-letter word guessing puzzle game', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['워들', 'wordle', '단어', '퍼즐', '게임', 'game'] },
  { slug: 'counter', category: 'utility', emoji: '🔢', labelKey: 'UtilityBoard.counter.title', href: '/utilities/utility/counter', available: true, icon: 'Hash', nameKo: '카운터', nameEn: 'Counter', descKo: '클릭 카운터 및 숫자 기록', descEn: 'Click counter and number tracker', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['카운터', 'counter', '숫자', '클릭', 'count'] },
  { slug: 'unit-converter', category: 'utility', emoji: '📏', labelKey: 'UtilityBoard.unit-converter.title', href: '/utilities/utility/unit-converter', available: true, icon: 'Ruler', nameKo: '단위 변환기', nameEn: 'Unit Converter', descKo: '길이·무게·온도 등 단위 변환', descEn: 'Convert length, weight, temperature units', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['단위', '변환', '미터', '파운드', '온도', 'unit', 'converter', 'km', 'mile'] },
  { slug: 'yt-thumbnail', category: 'utility', emoji: '📺', labelKey: 'UtilityBoard.yt-thumbnail.title', href: '/utilities/utility/yt-thumbnail', available: true, icon: 'PlayCircle', nameKo: '유튜브 썸네일 추출', nameEn: 'YouTube Thumbnail Extractor', descKo: '유튜브 영상 썸네일 이미지 추출', descEn: 'Extract thumbnail images from YouTube videos', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['유튜브', '썸네일', 'youtube', 'thumbnail', '이미지'] },
  { slug: 'pyeong-calc', category: 'utility', emoji: '🏠', labelKey: 'UtilityBoard.pyeong-calc.title', href: '/utilities/utility/pyeong-calc', available: true, icon: 'Home', nameKo: '평수 계산기', nameEn: 'Pyeong Calculator', descKo: '평·제곱미터 면적 변환 계산', descEn: 'Convert pyeong to square meters', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['평수', '제곱미터', '평', '면적', 'pyeong', 'sqm', '부동산'] },
  { slug: 'image-processor', category: 'utility', emoji: '🖼️', labelKey: 'UtilityBoard.image-processor.title', href: '/utilities/utility/image-processor', available: true, icon: 'ImagePlus', nameKo: '이미지 프로세서', nameEn: 'Image Processor', descKo: '이미지 색상·필터·효과 편집', descEn: 'Edit image colors, filters and effects', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['이미지', '사진', '편집', '필터', 'image', 'filter', 'edit'] },
  { slug: 'lotto-generator', category: 'utility', emoji: '🎰', labelKey: 'UtilityBoard.lotto-generator.title', href: '/utilities/utility/lotto-generator', available: true, icon: 'Dice5', nameKo: '로또 번호 생성기', nameEn: 'Lotto Number Generator', descKo: '랜덤 로또 번호 자동 생성', descEn: 'Generate random lottery numbers', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['로또', 'lotto', '번호', 'random', '복권', 'lottery'] },
  { slug: 'decision-master', category: 'utility', emoji: '🎡', labelKey: 'UtilityBoard.decision-master.title', href: '/utilities/utility/decision-master', available: true, icon: 'HelpCircle', nameKo: '결정 도우미', nameEn: 'Decision Master', descKo: '결정 장애 해결 랜덤 선택기', descEn: 'Random decision picker for the undecided', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['결정', '랜덤', '선택', 'decision', 'random', 'wheel'] },
  { slug: 'grid-poker', category: 'utility', emoji: '🃏', labelKey: 'UtilityBoard.grid-poker.title', href: '/utilities/utility/grid-poker', available: true, icon: 'CircleDot', nameKo: '그리드 포커', nameEn: 'Grid Poker', descKo: '격자 기반 포커 카드 게임', descEn: 'Grid-based poker card game', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['포커', '게임', '카드', 'poker', 'card', 'game'] },
  { slug: 'gif-master', category: 'utility', emoji: '🎞️', labelKey: 'UtilityBoard.gif-master.title', href: '/utilities/utility/gif-master', available: true, icon: 'Film', nameKo: 'GIF 생성기', nameEn: 'GIF Maker', descKo: '이미지로 GIF 애니메이션 생성', descEn: 'Create GIF animations from images', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['gif', '애니메이션', 'animation', '이미지', 'maker'] },
  { slug: 'cable-tray-calc', category: 'utility', emoji: '📐', labelKey: 'UtilityBoard.cable-tray-calc.title', href: '/utilities/utility/cable-tray-calc', available: true, icon: 'Cable', nameKo: '케이블 트레이 계산기', nameEn: 'Cable Tray Calculator', descKo: '전선 케이블 트레이 용량 계산', descEn: 'Calculate cable tray capacity', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['케이블', '트레이', '전선', 'cable', 'tray', '전기'] },
  { slug: 'wire-size-calc', category: 'utility', emoji: '⚡', labelKey: 'UtilityBoard.wire-size-calc.title', href: '/utilities/utility/wire-size-calc', available: true, icon: 'Zap', nameKo: '전선 굵기 계산기', nameEn: 'Wire Size Calculator', descKo: '전선 단면적 및 굵기 선정', descEn: 'Select wire size and cross-section', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['전선', '굵기', '단면적', 'wire', 'cable', '전기', 'ampere'] },
  { slug: 'interior-material-calc', category: 'utility', emoji: '🪟', labelKey: 'UtilityBoard.interior-material-calc.title', href: '/utilities/utility/interior-material-calc', available: true, icon: 'Layers', nameKo: '인테리어 자재 계산기', nameEn: 'Interior Material Calculator', descKo: '바닥·벽 시공 자재 수량 계산', descEn: 'Calculate flooring and wall material quantities', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['인테리어', '자재', '바닥', '벽', 'interior', 'flooring', 'tile'] },
  { slug: 'image-resizer', category: 'utility', emoji: '🔲', labelKey: 'UtilityBoard.image-resizer.title', href: '/utilities/utility/image-resizer', available: true, icon: 'Maximize2', nameKo: '이미지 리사이저', nameEn: 'Image Resizer', descKo: '이미지 크기 조정 및 비율 변환', descEn: 'Resize images and adjust aspect ratio', categoryNameKo: '유틸리티/게임', categoryNameEn: 'Utility', searchKeywords: ['이미지', '리사이즈', '크기', 'resize', 'image', 'width', 'height'] },

  // Dev
  { slug: 'json-formatter', category: 'dev', emoji: '🗂️', labelKey: 'DevBoard.json-formatter.title', href: '/utilities/dev/json-formatter', available: true, icon: 'Braces', nameKo: 'JSON 포매터', nameEn: 'JSON Formatter', descKo: 'JSON 파싱·포맷·검증 도구', descEn: 'Parse, format and validate JSON', categoryNameKo: '개발자 도구', categoryNameEn: 'Dev Tools', searchKeywords: ['json', '포맷', 'formatter', '파싱', 'parse', '개발'] },
  { slug: 'regex-tester', category: 'dev', emoji: '🔍', labelKey: 'DevBoard.regex-tester.title', href: '/utilities/dev/regex-tester', available: true, icon: 'Search', nameKo: '정규식 테스터', nameEn: 'Regex Tester', descKo: '정규 표현식 실시간 테스트', descEn: 'Test regular expressions in real time', categoryNameKo: '개발자 도구', categoryNameEn: 'Dev Tools', searchKeywords: ['정규식', 'regex', 'regexp', '패턴', 'pattern', '개발'] },
  { slug: 'resistor-calc', category: 'dev', emoji: '📟', labelKey: 'DevBoard.resistor-calc.title', href: '/utilities/dev/resistor-calc', available: true, icon: 'Cpu', nameKo: '저항 계산기', nameEn: 'Resistor Calculator', descKo: '저항 컬러코드 값 계산', descEn: 'Calculate resistor color code values', categoryNameKo: '개발자 도구', categoryNameEn: 'Dev Tools', searchKeywords: ['저항', '컬러코드', 'resistor', 'ohm', '전자', 'electronics'] },
  { slug: 'password-strength', category: 'dev', emoji: '🛡️', labelKey: 'DevBoard.password-strength.title', href: '/utilities/dev/password-strength', available: true, icon: 'Lock', nameKo: '비밀번호 강도 측정', nameEn: 'Password Strength Checker', descKo: '비밀번호 보안 강도 분석', descEn: 'Analyze password security strength', categoryNameKo: '개발자 도구', categoryNameEn: 'Dev Tools', searchKeywords: ['비밀번호', '강도', '보안', 'password', 'strength', 'security'] },
  { slug: 'kec-grounding', category: 'dev', emoji: '⚡', labelKey: 'DevBoard.kec-grounding.title', href: '/utilities/dev/kec-grounding', available: true, icon: 'Zap', nameKo: 'KEC 접지 계산기', nameEn: 'KEC Grounding Calculator', descKo: '한국전기설비규정 접지 계산', descEn: 'Calculate grounding per Korean electrical code', categoryNameKo: '개발자 도구', categoryNameEn: 'Dev Tools', searchKeywords: ['kec', '접지', 'grounding', '전기', 'electrical', '한국전기'] },
];
