'use client';

import React, { useCallback, useMemo, useState } from 'react';
import { useLocale, useTranslations } from 'next-intl';
import { ShieldOff, Copy, Check, Download, ChevronDown, ChevronRight } from 'lucide-react';
import NavigationActions from '@/app/components/NavigationActions';
import SeoSection from '@/app/components/SeoSection';
import RelatedTools from '@/app/components/RelatedTools';
import ShareBar from '@/app/components/ShareBar';
import { AI_BOTS, normalizePaths, hasWildcard, type AiBot } from '@/lib/ai-bots';
import s from './block-ai-crawlers.module.css';

type Scope = 'all' | 'folder' | 'image';
type Output = 'robots' | 'meta' | 'header' | 'llms';
type HeaderPlatform = 'apache' | 'nginx';

const MAJOR_IDS = AI_BOTS.filter((b) => b.major).map((b) => b.id);

export default function BlockAiCrawlersClient() {
  const t = useTranslations('BlockAiCrawlers');
  const locale = useLocale();
  const isKo = locale === 'ko';

  const [selected, setSelected] = useState<Set<string>>(() => new Set(MAJOR_IDS));
  const [moreOpen, setMoreOpen] = useState(false);
  const [scope, setScope] = useState<Scope>('all');
  const [folderInput, setFolderInput] = useState('');
  const [output, setOutput] = useState<Output>('robots');
  const [headerPlatform, setHeaderPlatform] = useState<HeaderPlatform>('apache');
  const [copied, setCopied] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  const showToast = useCallback((msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2600);
  }, []);

  const toggleBot = (id: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const selectMajor = () => setSelected(new Set(MAJOR_IDS));
  const deselectAll = () => setSelected(new Set());

  const selectedBots = useMemo(
    () => AI_BOTS.filter((b) => selected.has(b.id)),
    [selected],
  );
  const moreSelectedCount = useMemo(
    () => AI_BOTS.filter((b) => !b.major && selected.has(b.id)).length,
    [selected],
  );

  const folderPaths = useMemo(() => normalizePaths(folderInput), [folderInput]);
  const wildcardWarn = scope === 'folder' && hasWildcard(folderInput);

  // 폴더 입력 정규화 (onBlur)
  const handleFolderBlur = () => {
    if (scope !== 'folder') return;
    const trimmed = folderInput.trim();
    if (!trimmed) {
      setScope('all');
      showToast(t('path_empty_changed'));
      return;
    }
    const paths = normalizePaths(folderInput);
    if (paths.length === 0) {
      setScope('all');
      showToast(t('path_empty_changed'));
      return;
    }
    const normalized = paths.join(', ');
    if (normalized !== trimmed) {
      setFolderInput(normalized);
      showToast(t('path_normalized', { path: normalized }));
    }
  };

  // ── 코드 생성 ────────────────────────────────────────────────
  const generatedCode = useMemo(() => {
    if (selectedBots.length === 0) return '';

    // 산출물 생성 직전 한 번 더 정규화 (이중 안전)
    const paths = scope === 'folder' ? normalizePaths(folderInput) : [];
    const effectiveScope: Scope = scope === 'folder' && paths.length === 0 ? 'all' : scope;

    const disallowLines = (): string[] => {
      if (effectiveScope === 'all') return ['Disallow: /'];
      if (effectiveScope === 'image') {
        return ['Disallow: /*.jpg$', 'Disallow: /*.jpeg$', 'Disallow: /*.png$', 'Disallow: /*.gif$', 'Disallow: /*.webp$', 'Disallow: /*.svg$'];
      }
      return paths.map((p) => `Disallow: ${p}`);
    };

    if (output === 'robots') {
      const blocks = selectedBots.map((b) => {
        const lines = [`User-agent: ${b.userAgent}`, ...disallowLines()];
        return lines.join('\n');
      });
      return `# AI crawler blocking — generated by theutilhub.com\n# Normal search engines (Googlebot, Bingbot) are NOT affected.\n\n${blocks.join('\n\n')}`;
    }

    if (output === 'meta') {
      // 메타태그는 페이지 단위 — noai/noimageai
      const content = effectiveScope === 'image' ? 'noimageai' : 'noai, noimageai';
      return `<!-- Add inside <head> of each HTML page -->\n<meta name="robots" content="${content}">`;
    }

    if (output === 'header') {
      const headerVal = effectiveScope === 'image' ? 'noimageai' : 'noai, noimageai';
      if (headerPlatform === 'apache') {
        if (effectiveScope === 'folder' && paths.length > 0) {
          return paths
            .map((p) => `<Directory "/var/www/html${p}">\n  Header set X-Robots-Tag "${headerVal}"\n</Directory>`)
            .join('\n');
        }
        return `# Apache — add to .htaccess or httpd.conf\nHeader set X-Robots-Tag "${headerVal}"`;
      }
      // nginx
      if (effectiveScope === 'folder' && paths.length > 0) {
        return paths
          .map((p) => `location ${p} {\n  add_header X-Robots-Tag "${headerVal}";\n}`)
          .join('\n');
      }
      return `# Nginx — add to server block, then reload\nadd_header X-Robots-Tag "${headerVal}";`;
    }

    // llms.txt
    return `# llms.txt — AI usage policy for theutilhub.com\n# Generated by theutilhub.com\n\nUser-agent: *\nDisallow: /\n\n# Explicitly blocked AI crawlers:\n${selectedBots.map((b) => `# - ${b.userAgent} (${b.company})`).join('\n')}`;
  }, [selectedBots, scope, folderInput, output, headerPlatform]);

  const handleCopy = async () => {
    if (!generatedCode) return;
    try {
      await navigator.clipboard.writeText(generatedCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      showToast(t('copy_fallback'));
    }
  };

  const handleDownload = () => {
    if (!generatedCode) return;
    const filename =
      output === 'robots' ? 'robots.txt' :
      output === 'llms' ? 'llms.txt' :
      output === 'meta' ? 'ai-block-meta.html' :
      headerPlatform === 'apache' ? '.htaccess' : 'nginx-ai-block.conf';
    const blob = new Blob([generatedCode], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const noBots = selectedBots.length === 0;

  // 출력별 가이드/경고
  const guide = useMemo(() => {
    if (output === 'robots') return t('guide_robots');
    if (output === 'meta') return t('guide_meta');
    if (output === 'llms') return t('guide_llms');
    return headerPlatform === 'apache' ? t('guide_header_apache') : t('guide_header_nginx');
  }, [output, headerPlatform, t]);

  // 폴더 차단 + meta/llms 부적합 경고
  const scopeMismatchWarning = useMemo(() => {
    if (scope !== 'folder') return null;
    if (output === 'meta') return t('meta_folder_warning');
    if (output === 'llms') return t('llms_folder_warning');
    return null;
  }, [scope, output, t]);

  const trustBadge = isKo ? '표준 robots.txt 규격' : 'Standard robots.txt spec';

  const renderBotCard = (bot: AiBot) => (
    <label
      key={bot.id}
      className={`${s.bot_card} ${selected.has(bot.id) ? s.bot_card_active : ''}`}
    >
      <input
        type="checkbox"
        className={s.bot_checkbox}
        checked={selected.has(bot.id)}
        onChange={() => toggleBot(bot.id)}
        aria-label={bot.userAgent}
      />
      <span className={s.bot_info}>
        <span className={s.bot_name}>{bot.userAgent}</span>
        <span className={s.bot_company}>{bot.company} · {isKo ? bot.purposeKo : bot.purposeEn}</span>
      </span>
    </label>
  );

  return (
    <div className={s.container}>
      <NavigationActions />

      <header className={s.header}>
        <div style={{
          display: 'inline-flex', padding: '1rem', background: 'white',
          borderRadius: '1.5rem', boxShadow: '0 4px 12px rgba(0,0,0,0.05)', marginBottom: '1rem',
        }}>
          <ShieldOff size={38} color="#8b5cf6" />
        </div>
        <h1 className={s.title}>{t('title')}</h1>
        <p className={s.subtitle}>{t('subtitle')}</p>
      </header>

      {/* STEP 1: 봇 선택 */}
      <section className={s.panel}>
        <div className={s.section_title}>{t('step_bots')}</div>
        <div className={s.bot_actions}>
          <button className={s.bot_action_btn} onClick={selectMajor}>{t('select_all_major')}</button>
          <button className={s.bot_action_btn} onClick={deselectAll}>{t('deselect_all')}</button>
        </div>

        <div className={s.bot_group_label}>{t('bots_major')}</div>
        <div className={s.bot_grid}>
          {AI_BOTS.filter((b) => b.major).map(renderBotCard)}
        </div>

        <div className={s.accordion_header} onClick={() => setMoreOpen((v) => !v)} role="button" aria-expanded={moreOpen}>
          <span className={s.bot_group_label} style={{ margin: 0 }}>
            {moreOpen ? <ChevronDown size={14} style={{ display: 'inline', verticalAlign: 'middle' }} /> : <ChevronRight size={14} style={{ display: 'inline', verticalAlign: 'middle' }} />}
            {' '}{t('bots_more')}
          </span>
          <span className={s.accordion_count}>{t('bots_more_count', { n: moreSelectedCount })}</span>
        </div>
        {moreOpen && (
          <div className={s.bot_grid} style={{ marginTop: '0.6rem' }}>
            {AI_BOTS.filter((b) => !b.major).map(renderBotCard)}
          </div>
        )}
      </section>

      {/* STEP 2: 차단 범위 */}
      <section className={s.panel}>
        <div className={s.section_title}>{t('step_scope')}</div>
        <div className={s.scope_list}>
          {([
            ['all', t('scope_all'), t('scope_all_desc')],
            ['folder', t('scope_folder'), t('scope_folder_desc')],
            ['image', t('scope_image'), t('scope_image_desc')],
          ] as [Scope, string, string][]).map(([val, label, desc]) => (
            <label key={val} className={`${s.scope_card} ${scope === val ? s.scope_card_active : ''}`}>
              <input
                type="radio"
                className={s.scope_radio}
                checked={scope === val}
                onChange={() => setScope(val)}
                aria-label={label}
              />
              <span>
                <span className={s.scope_label}>{label}</span>
                <span className={s.scope_desc}>{desc}</span>
              </span>
            </label>
          ))}
        </div>

        {scope === 'folder' && (
          <div className={s.folder_input_wrap}>
            <input
              type="text"
              className={s.folder_input}
              value={folderInput}
              onChange={(e) => setFolderInput(e.target.value)}
              onBlur={handleFolderBlur}
              placeholder={t('folder_placeholder')}
              aria-label={t('scope_folder')}
            />
            {wildcardWarn && <div className={s.wildcard_warning} aria-live="polite">{t('path_wildcard_warning')}</div>}
          </div>
        )}
      </section>

      {/* STEP 3: 산출물 */}
      <section className={`${s.panel} ${s.output_section}`}>
        <div className={s.section_title}>{t('step_output')}</div>
        <div className={s.output_tabs}>
          {([
            ['robots', t('output_robots')],
            ['meta', t('output_meta')],
            ['header', t('output_header')],
            ['llms', t('output_llms')],
          ] as [Output, string][]).map(([val, label]) => (
            <button
              key={val}
              className={`${s.output_tab} ${output === val ? s.output_tab_active : ''}`}
              onClick={() => setOutput(val)}
              aria-label={label}
            >
              {label}
            </button>
          ))}
        </div>

        {output === 'header' && (
          <div className={s.platform_sub_tabs}>
            {(['apache', 'nginx'] as HeaderPlatform[]).map((p) => (
              <button
                key={p}
                className={`${s.platform_sub_tab} ${headerPlatform === p ? s.platform_sub_tab_active : ''}`}
                onClick={() => setHeaderPlatform(p)}
                aria-label={p}
              >
                {p === 'apache' ? 'Apache' : 'Nginx'}
              </button>
            ))}
          </div>
        )}

        {/* 코드 박스 */}
        <div className={s.code_wrap}>
          <div className={s.code_toolbar}>
            <span className={s.trust_badge}>{trustBadge}</span>
            <div className={s.toolbar_actions}>
              <button
                className={`${s.tool_btn} ${copied ? s.tool_btn_done : ''}`}
                onClick={handleCopy}
                disabled={noBots}
                aria-disabled={noBots}
                aria-label={t('copy_btn')}
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? t('copy_done') : t('copy_btn')}
              </button>
              <button
                className={s.tool_btn}
                onClick={handleDownload}
                disabled={noBots}
                aria-disabled={noBots}
                aria-label={t('download_btn')}
              >
                <Download size={14} />
                {t('download_btn')}
              </button>
            </div>
          </div>
          <pre className={s.code_body} role="textbox" aria-readonly="true" aria-live="polite">
            {generatedCode || ' '}
          </pre>
        </div>

        {/* 봇 0개 오버레이 */}
        {noBots && (
          <div className={s.no_bots_overlay} role="status" aria-live="polite">
            <div className={s.no_bots_msg}>{t('no_bots_title')}</div>
            <button className={s.no_bots_recover_btn} onClick={selectMajor}>{t('no_bots_recover')}</button>
          </div>
        )}

        {scopeMismatchWarning && <div className={s.danger_box}>{scopeMismatchWarning}</div>}
        {!noBots && <div className={s.guide_box}>{guide}</div>}
      </section>

      {/* AI 봇별 차단 효과 표 */}
      <section className={s.panel}>
        <div className={s.section_title}>{t('effect_title')}</div>
        <div className={s.effect_table_wrap}>
          <table className={s.effect_table}>
            <thead>
              <tr>
                <th>{t('effect_bot')}</th>
                <th>{t('effect_company')}</th>
                <th>{t('effect_purpose')}</th>
              </tr>
            </thead>
            <tbody>
              {selectedBots.map((b) => (
                <tr key={b.id}>
                  <td className={s.effect_bot_name}>{b.userAgent}</td>
                  <td>{b.company}</td>
                  <td>{isKo ? b.purposeKo : b.purposeEn}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* 검증 안내 */}
      <section className={s.panel}>
        <div className={s.section_title}>{t('verify_title')}</div>
        <div className={s.verify_box}>{t('verify_desc')}</div>
      </section>

      {toast && <div className={s.toast}>{toast}</div>}

      <ShareBar title={t('title')} description={t('subtitle')} />
      <RelatedTools toolId="utilities/security/block-ai-crawlers" />
      <div className={s.ad_placeholder}>{t('ad_text')}</div>

      <SeoSection
        ko={{
          title: 'AI 학습 차단 코드 생성기란?',
          description:
            'AI 학습 차단 코드 생성기는 OpenAI(GPTBot), Anthropic(ClaudeBot), Google(Google-Extended), Meta, Perplexity 등 주요 AI 크롤러가 내 웹사이트 콘텐츠를 학습 데이터로 무단 수집하는 것을 표준 방식으로 차단하는 코드를 만들어주는 도구입니다. 차단할 봇을 고르고 차단 범위(전체 사이트·특정 폴더·이미지)와 산출물 종류(robots.txt·HTML 메타태그·서버 헤더·llms.txt)를 선택하면 즉시 붙여넣을 수 있는 코드가 생성됩니다. 중요한 점은 이 차단이 구글·빙 같은 일반 검색 엔진의 색인에는 전혀 영향을 주지 않는다는 것입니다 — Googlebot과 Google-Extended는 별개의 봇이라, 검색 노출은 유지하면서 AI 학습만 선택적으로 막을 수 있습니다. 모든 코드 생성은 100% 브라우저에서 이루어지며 입력한 경로나 설정이 서버로 전송되지 않습니다. 18종 이상의 AI 봇 데이터베이스와 봇별 용도 설명, 적용 가이드까지 함께 제공합니다.',
          useCases: [
            { icon: '✍️', title: '블로그·창작물 보호', desc: '직접 쓴 글, 그림, 사진이 AI 학습 데이터로 무단 사용되는 것을 막아 창작물의 가치를 지킵니다. robots.txt 한 줄로 전체 콘텐츠를 보호합니다.' },
            { icon: '🏢', title: '기업 사이트 정책 적용', desc: '회사 웹사이트의 제품 정보·문서가 경쟁사 AI나 무단 학습에 사용되지 않도록 표준 차단 정책을 적용합니다. 검색 노출은 그대로 유지됩니다.' },
            { icon: '🖼️', title: '이미지 무단 학습 차단', desc: '포트폴리오·작품 이미지가 이미지 생성 AI의 학습 데이터로 수집되는 것을 차단합니다. 텍스트는 허용하고 이미지만 선택적으로 막을 수 있습니다.' },
            { icon: '📁', title: '특정 폴더만 선택 차단', desc: '유료 콘텐츠나 회원 전용 영역(/premium/, /members/)만 AI 학습에서 제외하고, 공개 영역은 그대로 두는 세밀한 정책을 구성합니다.' },
          ],
          steps: [
            { step: '차단할 AI 봇 선택', desc: '메이저 8개(GPTBot·ClaudeBot·Google-Extended 등)가 기본 선택되어 있습니다. 추가 봇 아코디언을 펼쳐 더 많은 봇을 선택하거나, 빠른 버튼으로 일괄 선택·해제할 수 있습니다.' },
            { step: '차단 범위 결정', desc: '전체 사이트, 특정 폴더, 이미지만 중에서 선택합니다. 특정 폴더는 입력창에서 벗어나면 경로가 자동으로 /blog/ 형식으로 정규화되며, 쉼표로 여러 폴더를 지정할 수 있습니다.' },
            { step: '산출물 형식 선택', desc: 'robots.txt가 가장 표준적이며 권장됩니다. HTML 메타태그, 서버 헤더(Apache·Nginx), llms.txt 중 자신의 환경에 맞는 형식을 탭으로 선택합니다.' },
            { step: '복사 후 적용', desc: '생성된 코드를 복사하거나 파일로 다운로드합니다. robots.txt는 사이트 루트에 업로드하고, 배포 후 yoursite.com/robots.txt로 접속해 적용을 확인합니다.' },
          ],
          faqs: [
            { q: 'AI 학습을 막으면 구글 검색에서도 사라지나요?', a: '아니요. Google-Extended(AI 학습용 봇)와 Googlebot(검색 색인용 봇)은 완전히 별개입니다. 본 도구는 AI 학습 봇만 차단하므로 구글·빙 일반 검색 노출은 100% 유지됩니다. 검색 트래픽 손실 없이 AI 학습만 선택적으로 막을 수 있습니다.' },
            { q: 'robots.txt로 정말 AI 봇을 막을 수 있나요?', a: 'robots.txt는 강제력이 아닌 "정중한 요청" 표준입니다. OpenAI, Anthropic, Google 등 주요 AI 기업은 공식적으로 robots.txt를 준수한다고 명시하고 있어 대부분의 메이저 봇은 차단됩니다. 다만 일부 비양심적 봇은 무시할 수 있어, 더 강한 차단이 필요하면 서버 헤더(X-Robots-Tag)나 방화벽 차단을 병행하세요.' },
            { q: 'robots.txt와 메타태그, 서버 헤더 중 뭘 써야 하나요?', a: 'robots.txt가 가장 표준적이고 사이트 전체에 한 번에 적용되어 권장됩니다. 특정 폴더만 막으려면 robots.txt나 서버 헤더가 적합합니다. HTML 메타태그는 페이지 단위라 폴더 차단에는 부적합합니다. llms.txt는 신생 표준으로 AI 정책을 명시하는 보조 수단입니다.' },
            { q: '이 툴의 결과를 공식 자료로 사용해도 되나요?', a: '본 도구는 표준 규격에 기반한 코드를 생성하지만, AI 봇 정책은 수시로 변하고 봇별 준수 여부가 다릅니다. 법적 효력이 필요한 저작권 보호에는 robots.txt만으로 충분하지 않으므로, 중요한 콘텐츠는 이용약관 명시·DRM·법적 조치 등 추가 수단을 병행하시기 바랍니다.' },
          ],
        }}
        en={{
          title: 'What is the Block AI Crawlers Code Generator?',
          description:
            "The Block AI Crawlers Code Generator creates standards-based code to stop major AI crawlers — OpenAI (GPTBot), Anthropic (ClaudeBot), Google (Google-Extended), Meta, Perplexity, and more — from scraping your website content as training data. Choose which bots to block, the scope (entire site, specific folders, or images only), and the output type (robots.txt, HTML meta tag, server header, or llms.txt), and ready-to-paste code is generated instantly. Crucially, this blocking does NOT affect indexing by normal search engines like Google or Bing — Googlebot and Google-Extended are separate bots, so you keep your search visibility while selectively blocking only AI training. All code generation happens 100% in your browser; your paths and settings are never sent to a server. Includes a database of 18+ AI bots with per-bot purpose descriptions and application guides.",
          useCases: [
            { icon: '✍️', title: 'Protect Blogs & Creative Work', desc: 'Prevent your articles, art, and photos from being scraped as AI training data, preserving the value of your creative work — a single robots.txt line protects everything.' },
            { icon: '🏢', title: 'Corporate Site Policy', desc: 'Apply a standard blocking policy so your company\'s product info and docs are not used for competitor AI or unauthorized training, while keeping search visibility intact.' },
            { icon: '🖼️', title: 'Block Image Scraping', desc: 'Stop your portfolio and artwork images from being collected for image-generation AI training. Allow text while selectively blocking images only.' },
            { icon: '📁', title: 'Block Specific Folders', desc: 'Exclude only paid content or members-only areas (/premium/, /members/) from AI training while leaving public areas open — fine-grained control.' },
          ],
          steps: [
            { step: 'Select AI bots to block', desc: 'The 8 major bots (GPTBot, ClaudeBot, Google-Extended, etc.) are selected by default. Expand the "More bots" accordion for additional bots, or use the quick buttons to select/deselect all.' },
            { step: 'Choose block scope', desc: 'Pick entire site, specific folders, or images only. For folders, the path auto-normalizes to /blog/ format on blur, and you can specify multiple folders comma-separated.' },
            { step: 'Pick the output format', desc: 'robots.txt is the most standard and recommended. Switch tabs to HTML meta tag, server header (Apache/Nginx), or llms.txt depending on your environment.' },
            { step: 'Copy and apply', desc: 'Copy the generated code or download it as a file. Upload robots.txt to your site root, then visit yoursite.com/robots.txt after deployment to confirm it works.' },
          ],
          faqs: [
            { q: 'If I block AI training, do I disappear from Google Search?', a: 'No. Google-Extended (AI training bot) and Googlebot (search indexing bot) are completely separate. This tool blocks only AI training bots, so your Google/Bing search visibility stays 100% intact. You can selectively block AI training with zero search traffic loss.' },
            { q: 'Does robots.txt really block AI bots?', a: 'robots.txt is a "polite request" standard, not enforcement. Major AI companies — OpenAI, Anthropic, Google — officially state they honor robots.txt, so most major bots are blocked. Some unscrupulous bots may ignore it; for stronger blocking, combine with server headers (X-Robots-Tag) or firewall rules.' },
            { q: 'Which should I use — robots.txt, meta tag, or server header?', a: 'robots.txt is the most standard and applies site-wide at once, so it is recommended. For folder-only blocking, robots.txt or server headers work best. HTML meta tags are per-page and unsuitable for folder blocking. llms.txt is an emerging standard for declaring AI policy.' },
            { q: 'Can I use this as official protection?', a: 'This tool generates standards-based code, but AI bot policies change frequently and compliance varies by bot. robots.txt alone is not sufficient for legally enforceable copyright protection, so combine it with terms-of-service notices, DRM, or legal measures for critical content.' },
          ],
        }}
      />
    </div>
  );
}
